title = "Publicaciones de interes para Hackers"                                                                
baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
 
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"
 
[languages]
  [languages.en]
    title = "esaleatorio.com"
    subtitle = "De interes para algunos Hackers"
    keywords = ""
    copyright = ""
    menuMore = "Ver mas"
    readMore = "Leer mas"
    readOtherPosts = "Otras publicaciones"
 
    [languages.en.params.logo]
      logoText = "es aleatorio"
      logoHomeLink = "/"
 
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Acerca de Nosotros"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

